export const PRELOAD_IMAGE_FILES = [
  "background.jpg",
  "catLeft.png",
  "catRight.png",
  "logo.png",
  "playerConnic.png",
  "playerConnicBottom.png",
  "playerConnicDead.png",
  "playerConnicEating.png",
  "playerConnicHead.png",
  "playerConnicHeadBack.png",
  "playerConnicLeft.png",
  "playerConnicRight.png",
  "playerConnicTop.png",
  "playerCovick.png",
  "playerCovickBottom.png",
  "playerCovickDead.png",
  "playerCovickEating.png",
  "playerCovickHead.png",
  "playerCovickHeadBack.png",
  "playerCovickLeft.png",
  "playerCovickRight.png",
  "playerCovickTop.png",
  "tutorial.png",
  "tvShow.gif"
];

export const COLORS = {
  black: "#000000",
  brown: "#655132",
  darkBlack: "#161A1E",
  darkBrown: "#3C2C13",
  darkestBrown: "#291d0a",
  gray: "#DDDDDD",
  lightBrown: "#7a623c",
  red: "#cc3300",
  turquoise: "#32ccd8",
  white: "#FFFFFF",
  yellow: "#ffcc00"
}
